const categories = {
	Marketing: [
		"Branding",
		"SEO",
		"Ads/Performance Marketing",
		"Email Marketing",
		"Social Media",
		"YouTube",
		"Instagram",
		"Facebook",
		"Twitter",
		"LinkedIn",
		"TikTok",
		"Pinterest",
		"Snapchat",
		"Reddit",
		"Quora",
		"Story Telling",
		"Content Writing",
		"Copywriting",
		"Summarizer",
		"Podcasts",
		"Other",
	],
	Sales: ["Outreach", "Automation", "Responses"],
	Product: ["Website Builder", "Landing pages", "Customer Development", "Analytics", "A/B Testing", "Other"],
	Developer: ["Code Assistant", "Developer Tools", "Low Code/No Code"],
	Data: ["Spreadsheets", "SQL"],
	Design: ["Presentations", "Thumbnails", "Design Assistant", "Logo Generator", "UI/UX", "Ad creatives"],
	Productivity: ["Work", "Personal", "Project Management", "Time Management", "Note Taking"],
	"Customer Support": [],
	Operations: [],
	HR: [],
	Legal: [],
	Video: ["Video Editing", "Video Generator", "Personalized Tools"],
	Audio: ["Text to Speech", "Audio Editing", "Music", "Transcriber"],
	Images: ["Image Generator", "Image Editing", "Avatars", "Art"],
	Text: [],
	"2-D": [],
	"3-D": [],
	Prompts: [],
	"Search Engine Results": [],
	Industries: [
		"Education",
		"Finance",
		"Real Estate",
		"Healthcare",
		"Gaming",
		"Fun",
		"Fashion",
		"B2B SAAS",
		"Travel",
		"Fitness",
		"Dating",
		"Religion",
		"Memory",
		"Fun Tools",
		"Mental Health",
	],
};

const tools = [
	{
		name: "BeachAI",
		url: "https://beachai.com",
		oneLiner: "BeachAI is a tool that helps you create a beach landing page in seconds",
		image: "https://everythingai.s3.ap-south-1.amazonaws.com/07c728d1-d819-44cc-a14b-365917e7b885.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "https://twitter.com/Pushpit07",
		instagram: "https://www.instagram.com/pushpit._.07",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "TowerAI",
		url: "https://towerai.com",
		oneLiner: "Tower ai helps you find nearest towers near you",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Stockimg AI",
		url: "https://stockimg.ai/",
		oneLiner: "Book Covers",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Scene One",
		url: "https://sceneone.app",
		oneLiner: "Write more stories + book writing tools",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Audioread",
		url: "https://audioread.com",
		oneLiner: "Turn your reads into podcasts",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Verb AI",
		url: "https://verb.ai",
		oneLiner: "Plan your book + community",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Taplio",
		url: "https://app.taplio.com",
		oneLiner: "Linkedin Ideas + Scheduling",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Salee Pro",
		url: "https://salee.pro",
		oneLiner: "Linkedin personalization",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Final Scout",
		url: "https://finalscout.com",
		oneLiner: "Linkedin reachout + Email finder",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Abney.ai",
		url: "https://www.abney.ai",
		oneLiner: "Write your podcast show notes",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Chat Shape",
		url: "https://www.chatshape.com",
		oneLiner: "Build AI Bots quickly",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Notion AI",
		url: "https://www.notion.so/product/ai?gspk=dml2ZWt2YXJtYTc0OTA&gsxid=ZjEehZIWjdBy&pscd=affiliate.notion.so&utm_medium=vivekvarma7490&utm_source=affl",
		oneLiner: "Notion AI Powered",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Searchable AI",
		url: "https://www.searchable.ai",
		oneLiner: "All Work data in one",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Snazzy.ai",
		url: "https://snazzy.ai",
		oneLiner: "Creating landing pages + Ads + AI",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Comment Analyzer",
		url: "https://www.commentanalyzer.com/",
		oneLiner: "Comment Analyzer on youtube",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Eightify App",
		url: "https://eightify.app/?",
		oneLiner: "Youtube Summaries",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Lemon Recruiter",
		url: "https://chrome.google.com/webstore/detail/lemonrecruiter/kbgdnekpkdbagiccakldjfmhmncdnphc",
		oneLiner: "Lemon Recruiter",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "AIxstock",
		url: "https://www.futurepedia.io/tool/aixstock",
		oneLiner: "Stock images",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Quickvid.ai",
		url: "https://www.quickvid.ai",
		oneLiner: "Youtube Shorts",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Beatoven.ai",
		url: "https://www.beatoven.ai",
		oneLiner: "Royalty Free music",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Aiwoo",
		url: "https://www.futurepedia.io/tool/aiwoo-powerfull-ai-content-generator-for-woocommerce",
		oneLiner: "Generate unique Product Descriptions",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
	{
		name: "Casper AI",
		url: "https://chrome.google.com/webstore/detail/casper-ai/fgfiokgecpkambjildjleljjcihnocel?utm_source=futurepedia&utm_medium=marketplace&utm_campaign=futurepedia",
		oneLiner: "Simplify Work extensions",
		image: "https://everythingai.s3.amazonaws.com/dba82405-541d-42ea-b523-bf2a0b059ee2.jpg",
		category: "",
		subCategory: "",
		pricing: "",
		twitter: "",
		instagram: "",
		linkedin: "",
		youtube: "",
		verified: true,
	},
];

module.exports = { categories, tools };
