const categories = {
	Marketing: [
		"Branding",
		"SEO",
		"Ads/Performance Marketing",
		"Email Marketing",
		"Social Media",
		"YouTube",
		"Instagram",
		"Facebook",
		"Twitter",
		"LinkedIn",
		"TikTok",
		"Pinterest",
		"Snapchat",
		"Reddit",
		"Quora",
		"Story Telling",
		"Content Writing",
		"Copywriting",
		"Summarizer",
		"Podcasts",
		"Other",
	],
	Sales: ["Outreach", "Automation", "Responses"],
	Product: ["Website Builder", "Landing pages", "Customer Development", "Analytics", "A/B Testing", "Other"],
	Developer: ["Code Assistant", "Developer Tools", "Low Code/No Code"],
	Data: ["Spreadsheets", "SQL"],
	Design: ["Presentations", "Thumbnails", "Design Assistant", "Logo Generator", "UI/UX", "Ad creatives"],
	Productivity: ["Work", "Personal", "Project Management", "Time Management", "Note Taking"],
	"Customer Support": [],
	Operations: [],
	HR: [],
	Legal: [],
	Video: ["Video Editing", "Video Generator", "Personalized Tools"],
	Audio: ["Text to Speech", "Audio Editing", "Music", "Transcriber"],
	Images: ["Image Generator", "Image Editing", "Avatars", "Art"],
	Text: [],
	"2-D": [],
	"3-D": [],
	Prompts: [],
	"Search Engine Results": [],
	Industries: [
		"Education",
		"Finance",
		"Real Estate",
		"Healthcare",
		"Gaming",
		"Fun",
		"Fashion",
		"B2B SAAS",
		"Travel",
		"Fitness",
		"Dating",
		"Religion",
		"Memory",
		"Fun Tools",
		"Mental Health",
	],
};

module.exports = { categories };
