export const CREATE_AI_RECOMMENDATION_REQUEST =
  "CREATE_AI_RECOMMENDATION_REQUEST";
export const CREATE_AI_RECOMMENDATION_SUCCESS =
  "CREATE_AI_RECOMMENDATION_SUCCESS";
export const CREATE_AI_RECOMMENDATION_FAIL = "CREATE_AI_RECOMMENDATION_FAIL";

export const GET_AI_RECOMMENDATIONS_REQUEST = "GET_AI_RECOMMENDATIONS_REQUEST";
export const GET_AI_RECOMMENDATIONS_SUCCESS = "GET_AI_RECOMMENDATIONS_SUCCESS";
export const GET_AI_RECOMMENDATIONS_FAIL = "GET_AI_RECOMMENDATIONS_FAIL";

export const DELETE_AI_RECOMMENDATION_REQUEST =
  "DELETE_AI_RECOMMENDATION_REQUEST";
export const DELETE_AI_RECOMMENDATION_SUCCESS =
  "DELETE_AI_RECOMMENDATION_SUCCESS";
export const DELETE_AI_RECOMMENDATION_RESET = "DELETE_AI_RECOMMENDATION_RESET";
export const DELETE_AI_RECOMMENDATION_FAIL = "DELETE_AI_RECOMMENDATION_FAIL";

export const GET_AI_RECOMMENDATION_REQUEST = "GET_AI_RECOMMENDATION_REQUEST";
export const GET_AI_RECOMMENDATION_SUCCESS = "GET_AI_RECOMMENDATION_SUCCESS";
export const GET_AI_RECOMMENDATION_FAIL = "GET_AI_RECOMMENDATION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
