export const CREATE_COLLECTION_REQUEST = "CREATE_COLLECTION_REQUEST";
export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
export const CREATE_COLLECTION_FAIL = "CREATE_COLLECTION_FAIL";

export const GET_COLLECTIONS_REQUEST = "GET_COLLECTIONS_REQUEST";
export const GET_COLLECTIONS_SUCCESS = "GET_COLLECTIONS_SUCCESS";
export const GET_COLLECTIONS_FAIL = "GET_COLLECTIONS_FAIL";

export const UPDATE_COLLECTION_REQUEST = "UPDATE_COLLECTION_REQUEST";
export const UPDATE_COLLECTION_SUCCESS = "UPDATE_COLLECTION_SUCCESS";
export const UPDATE_COLLECTION_RESET = "UPDATE_COLLECTION_RESET";
export const UPDATE_COLLECTION_FAIL = "UPDATE_COLLECTION_FAIL";

export const DELETE_COLLECTION_REQUEST = "DELETE_COLLECTION_REQUEST";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_RESET = "DELETE_COLLECTION_RESET";
export const DELETE_COLLECTION_FAIL = "DELETE_COLLECTION_FAIL";

export const GET_COLLECTION_REQUEST = "GET_COLLECTION_REQUEST";
export const GET_COLLECTION_SUCCESS = "GET_COLLECTION_SUCCESS";
export const GET_COLLECTION_FAIL = "GET_COLLECTION_FAIL";

export const ADD_TOOL_TO_COLLECTION_REQUEST = "ADD_TOOL_TO_COLLECTION_REQUEST";
export const ADD_TOOL_TO_COLLECTION_SUCCESS = "ADD_TOOL_TO_COLLECTION_SUCCESS";
export const ADD_TOOL_TO_COLLECTION_FAIL = "ADD_TOOL_TO_COLLECTION_FAIL";

export const REMOVE_TOOL_FROM_COLLECTION_REQUEST =
  "REMOVE_TOOL_FROM_COLLECTION_REQUEST";
export const REMOVE_TOOL_FROM_COLLECTION_SUCCESS =
  "REMOVE_TOOL_FROM_COLLECTION_SUCCESS";
export const REMOVE_TOOL_FROM_COLLECTION_FAIL =
  "REMOVE_TOOL_FROM_COLLECTION_FAIL";
export const REMOVE_TOOL_FROM_COLLECTION_RESET =
  "REMOVE_TOOL_FROM_COLLECTION_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
