export const CREATE_GEN_AI_PARTNER_REQUEST = "CREATE_GEN_AI_PARTNER_REQUEST";
export const CREATE_GEN_AI_PARTNER_SUCCESS = "CREATE_GEN_AI_PARTNER_SUCCESS";
export const CREATE_GEN_AI_PARTNER_FAIL = "CREATE_GEN_AI_PARTNER_FAIL";

export const GET_GEN_AI_PARTNERS_REQUEST = "GET_GEN_AI_PARTNERS_REQUEST";
export const GET_GEN_AI_PARTNERS_SUCCESS = "GET_GEN_AI_PARTNERS_SUCCESS";
export const GET_GEN_AI_PARTNERS_FAIL = "GET_GEN_AI_PARTNERS_FAIL";

export const GET_ADMIN_GEN_AI_PARTNERS_REQUEST = "GET_ADMIN_GEN_AI_PARTNERS_REQUEST";
export const GET_ADMIN_GEN_AI_PARTNERS_SUCCESS = "GET_ADMIN_GEN_AI_PARTNERS_SUCCESS";
export const GET_ADMIN_GEN_AI_PARTNERS_FAIL = "GET_ADMIN_GEN_AI_PARTNERS_FAIL";

export const GET_VERIFIED_GEN_AI_PARTNERS_REQUEST = "GET_VERIFIED_GEN_AI_PARTNERS_REQUEST";
export const GET_VERIFIED_GEN_AI_PARTNERS_SUCCESS = "GET_VERIFIED_GEN_AI_PARTNERS_SUCCESS";
export const GET_VERIFIED_GEN_AI_PARTNERS_FAIL = "GET_VERIFIED_GEN_AI_PARTNERS_FAIL";

export const GET_UNVERIFIED_GEN_AI_PARTNERS_REQUEST = "GET_UNVERIFIED_GEN_AI_PARTNERS_REQUEST";
export const GET_UNVERIFIED_GEN_AI_PARTNERS_SUCCESS = "GET_UNVERIFIED_GEN_AI_PARTNERS_SUCCESS";
export const GET_UNVERIFIED_GEN_AI_PARTNERS_FAIL = "GET_UNVERIFIED_GEN_AI_PARTNERS_FAIL";

export const UPDATE_GEN_AI_PARTNER_REQUEST = "UPDATE_GEN_AI_PARTNER_REQUEST";
export const UPDATE_GEN_AI_PARTNER_SUCCESS = "UPDATE_GEN_AI_PARTNER_SUCCESS";
export const UPDATE_GEN_AI_PARTNER_RESET = "UPDATE_GEN_AI_PARTNER_RESET";
export const UPDATE_GEN_AI_PARTNER_FAIL = "UPDATE_GEN_AI_PARTNER_FAIL";

export const DELETE_GEN_AI_PARTNER_REQUEST = "DELETE_GEN_AI_PARTNER_REQUEST";
export const DELETE_GEN_AI_PARTNER_SUCCESS = "DELETE_GEN_AI_PARTNER_SUCCESS";
export const DELETE_GEN_AI_PARTNER_RESET = "DELETE_GEN_AI_PARTNER_RESET";
export const DELETE_GEN_AI_PARTNER_FAIL = "DELETE_GEN_AI_PARTNER_FAIL";

export const VERIFY_GEN_AI_PARTNER_REQUEST = "VERIFY_GEN_AI_PARTNER_REQUEST";
export const VERIFY_GEN_AI_PARTNER_SUCCESS = "VERIFY_GEN_AI_PARTNER_SUCCESS";
export const VERIFY_GEN_AI_PARTNER_RESET = "VERIFY_GEN_AI_PARTNER_RESET";
export const VERIFY_GEN_AI_PARTNER_FAIL = "VERIFY_GEN_AI_PARTNER_FAIL";

export const UNVERIFY_GEN_AI_PARTNER_REQUEST = "UNVERIFY_GEN_AI_PARTNER_REQUEST";
export const UNVERIFY_GEN_AI_PARTNER_SUCCESS = "UNVERIFY_GEN_AI_PARTNER_SUCCESS";
export const UNVERIFY_GEN_AI_PARTNER_RESET = "UNVERIFY_GEN_AI_PARTNER_RESET";
export const UNVERIFY_GEN_AI_PARTNER_FAIL = "UNVERIFY_GEN_AI_PARTNER_FAIL";

export const GET_GEN_AI_PARTNER_REQUEST = "GET_GEN_AI_PARTNER_REQUEST";
export const GET_GEN_AI_PARTNER_SUCCESS = "GET_GEN_AI_PARTNER_SUCCESS";
export const GET_GEN_AI_PARTNER_FAIL = "GET_GEN_AI_PARTNER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
