export const CREATE_LIKED_TOOL_REQUEST = "CREATE_LIKED_TOOL_REQUEST";
export const CREATE_LIKED_TOOL_SUCCESS = "CREATE_LIKED_TOOL_SUCCESS";
export const CREATE_LIKED_TOOL_FAIL = "CREATE_LIKED_TOOL_FAIL";

export const DELETE_LIKED_TOOL_REQUEST = "DELETE_LIKED_TOOL_REQUEST";
export const DELETE_LIKED_TOOL_SUCCESS = "DELETE_LIKED_TOOL_SUCCESS";
export const DELETE_LIKED_TOOL_RESET = "DELETE_LIKED_TOOL_RESET";
export const DELETE_LIKED_TOOL_FAIL = "DELETE_LIKED_TOOL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
