export const CREATE_PRICING_REQUEST = "CREATE_PRICING_REQUEST";
export const CREATE_PRICING_SUCCESS = "CREATE_PRICING_SUCCESS";
export const CREATE_PRICING_FAIL = "CREATE_PRICING_FAIL";

export const GET_PRICINGS_REQUEST = "GET_PRICINGS_REQUEST";
export const GET_PRICINGS_SUCCESS = "GET_PRICINGS_SUCCESS";
export const GET_PRICINGS_FAIL = "GET_PRICINGS_FAIL";

export const UPDATE_PRICING_REQUEST = "UPDATE_PRICING_REQUEST";
export const UPDATE_PRICING_SUCCESS = "UPDATE_PRICING_SUCCESS";
export const UPDATE_PRICING_RESET = "UPDATE_PRICING_RESET";
export const UPDATE_PRICING_FAIL = "UPDATE_PRICING_FAIL";

export const DELETE_PRICING_REQUEST = "DELETE_PRICING_REQUEST";
export const DELETE_PRICING_SUCCESS = "DELETE_PRICING_SUCCESS";
export const DELETE_PRICING_RESET = "DELETE_PRICING_RESET";
export const DELETE_PRICING_FAIL = "DELETE_PRICING_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
