export const GET_PURCHASE_TERMS_REQUEST = "GET_PURCHASE_TERMS_REQUEST";
export const GET_PURCHASE_TERMS_SUCCESS = "GET_PURCHASE_TERMS_SUCCESS";
export const GET_PURCHASE_TERMS_FAIL = "GET_PURCHASE_TERMS_FAIL";

export const CREATE_PURCHASE_TERMS_REQUEST = "CREATE_PURCHASE_TERMS_REQUEST";
export const CREATE_PURCHASE_TERMS_SUCCESS = "CREATE_PURCHASE_TERMS_SUCCESS";
export const CREATE_PURCHASE_TERMS_FAIL = "CREATE_PURCHASE_TERMS_FAIL";

export const UPDATE_PURCHASE_TERMS_REQUEST = "UPDATE_PURCHASE_TERMS_REQUEST";
export const UPDATE_PURCHASE_TERMS_SUCCESS = "UPDATE_PURCHASE_TERMS_SUCCESS";
export const UPDATE_PURCHASE_TERMS_FAIL = "UPDATE_PURCHASE_TERMS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
