export const CREATE_TOOL_REQUEST = "CREATE_TOOL_REQUEST";
export const CREATE_TOOL_SUCCESS = "CREATE_TOOL_SUCCESS";
export const CREATE_TOOL_FAIL = "CREATE_TOOL_FAIL";

export const GET_TOOLS_REQUEST = "GET_TOOLS_REQUEST";
export const GET_TOOLS_SUCCESS = "GET_TOOLS_SUCCESS";
export const GET_TOOLS_FAIL = "GET_TOOLS_FAIL";

export const GET_ADMIN_TOOLS_REQUEST = "GET_ADMIN_TOOLS_REQUEST";
export const GET_ADMIN_TOOLS_SUCCESS = "GET_ADMIN_TOOLS_SUCCESS";
export const GET_ADMIN_TOOLS_FAIL = "GET_ADMIN_TOOLS_FAIL";

export const GET_VERIFIED_TOOLS_REQUEST = "GET_VERIFIED_TOOLS_REQUEST";
export const GET_VERIFIED_TOOLS_SUCCESS = "GET_VERIFIED_TOOLS_SUCCESS";
export const GET_VERIFIED_TOOLS_FAIL = "GET_VERIFIED_TOOLS_FAIL";

export const GET_UNVERIFIED_TOOLS_REQUEST = "GET_UNVERIFIED_TOOLS_REQUEST";
export const GET_UNVERIFIED_TOOLS_SUCCESS = "GET_UNVERIFIED_TOOLS_SUCCESS";
export const GET_UNVERIFIED_TOOLS_FAIL = "GET_UNVERIFIED_TOOLS_FAIL";

export const GET_TOOLS_FOR_HOMEPAGE_REQUEST = "GET_TOOLS_FOR_HOMEPAGE_REQUEST";
export const GET_TOOLS_FOR_HOMEPAGE_SUCCESS = "GET_TOOLS_FOR_HOMEPAGE_SUCCESS";
export const GET_TOOLS_FOR_HOMEPAGE_FAIL = "GET_TOOLS_FOR_HOMEPAGE_FAIL";

export const UPDATE_TOOL_REQUEST = "UPDATE_TOOL_REQUEST";
export const UPDATE_TOOL_SUCCESS = "UPDATE_TOOL_SUCCESS";
export const UPDATE_TOOL_RESET = "UPDATE_TOOL_RESET";
export const UPDATE_TOOL_FAIL = "UPDATE_TOOL_FAIL";

export const DELETE_TOOL_REQUEST = "DELETE_TOOL_REQUEST";
export const DELETE_TOOL_SUCCESS = "DELETE_TOOL_SUCCESS";
export const DELETE_TOOL_RESET = "DELETE_TOOL_RESET";
export const DELETE_TOOL_FAIL = "DELETE_TOOL_FAIL";

export const VERIFY_TOOL_REQUEST = "VERIFY_TOOL_REQUEST";
export const VERIFY_TOOL_SUCCESS = "VERIFY_TOOL_SUCCESS";
export const VERIFY_TOOL_RESET = "VERIFY_TOOL_RESET";
export const VERIFY_TOOL_FAIL = "VERIFY_TOOL_FAIL";

export const UNVERIFY_TOOL_REQUEST = "UNVERIFY_TOOL_REQUEST";
export const UNVERIFY_TOOL_SUCCESS = "UNVERIFY_TOOL_SUCCESS";
export const UNVERIFY_TOOL_RESET = "UNVERIFY_TOOL_RESET";
export const UNVERIFY_TOOL_FAIL = "UNVERIFY_TOOL_FAIL";

export const GET_TOOL_REQUEST = "GET_TOOL_REQUEST";
export const GET_TOOL_SUCCESS = "GET_TOOL_SUCCESS";
export const GET_TOOL_FAIL = "GET_TOOL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
